#!/usr/bin/env python3
"""
Web Warp / Web Wars (Vectrex, 1983)
Native Python 3 vector reconstruction — V8 foreground-web correction

V8 fixes the truncated foreground of the Web of Fantasy.

Important V8 behavior
---------------------
* the web camera motion remains the deterministic $191C script
* lateral Hawk movement does NOT pan/follow the web
* speed still controls the moving ring flow
* the normal 3-byte depth-ring pool remains unchanged
* after those rings, a separate foreground rail pass extends from the nearest
  active ring to a virtual fixed-$E0 front plane
* this mirrors the original renderer's separate post-ring pass that sets scale
  $E0 and calls the specialized $08CF transformed-web routine
* no extra front U-ring is drawn: only the longitudinal foreground rails extend
  toward/off the visible CRT area, avoiding the chopped-off look

Previously V7:


Critical V7 fixes
-----------------
* 720x960 portrait window retained
* removes V6's erroneous extra 0.75 beam shrink
* native beam mapping defaults to 1/64 logical pixel per (component*scale)
* front $E0 Web ring is ~560 px wide on 720 px canvas (~78%)
* anti-aliased line drawing replaces hard 1-pixel pygame.draw.line for width 1
* optional --beam-gain allows analogue-display calibration without touching ROM math
* gameplay/vector state remains in Vectrex integer units; gain is applied only at final display mapping

Previously V6:


Critical V6 fixes
-----------------
* portrait 720x960 (3:4) retained
* $094F corrected: ASRA and ASRB are independent byte shifts
* restored the missing camera PRE-MOVE at scale $7F before $094F
* exact 16-bit arithmetic midpoint used for initial Hawk coordinates
* Web-Line pool is prefilled before gameplay, like original $0239
* moving U-rings are again rendered as scaled $1177 packet vectors, not by
  passing each ring vertex through the object placement routine
* web and entity transforms are kept separate where the ROM keeps them separate
* all Pygame line output is clipped to the portrait screen
* window-close exits immediately and pygame cleanup is protected by finally

Important:
The digital game-coordinate pipeline is now substantially closer to the ROM.
The remaining non-bit-exact visual subsystem is $08CF, the direct VIA routine
that draws/transforms the longitudinal web rails.

Previously V5:


New in V5
---------
* true portrait 3:4 Vectrex-style window: 720 x 960
* one unified world->screen path for BOTH web and all game objects
* web vertices use the same BIOS transform + $094F + depth placement as entities
* Hawk/Guardian/Creature/Portal now lie on the actual displayed web geometry
* removed the separate heuristic web origin that caused visible displacement
* uniform Vectrex beam scaling in portrait space
* portrait HUD/title/status layout
* longitudinal web rails are generated by connecting identically transformed
  original $1177 world vertices across active depth records

V4 already added:


New in V4
---------
* exact 16-bit cumulative world vertices derived from ROM $1177
* exact motion-step tables equivalent to RAM $CA43/$CA60/$CA7D:
      Hawk King : web deltas * 8  -> 32 steps per segment
      Guardians : web deltas * 16 -> 16 steps per segment
      Creature  : web deltas * 32 ->  8 steps per segment
* Hawk King now moves continuously along the U-web instead of hopping lanes
* exact BIOS rotation_pair_table ($FC6D) loaded from the user's Vectrex BIOS
* Python implementations of:
      Get_Run_Idx
      Get_Rise_Idx
      Xform_Run_a
      Xform_Rise_a
  including the original 8x8 multiply rounding
* world-coordinate transform uses the same signed 8-bit high-byte math as ROM
* $094F BuildDrawDisplacement is emulated instruction-for-instruction closely
  enough to reconstruct the two relative beam moves used for object placement
* model rotation is done with BIOS-style integer transforms, not math.sin/cos
* depth update uses the original rounded:
      delta = (depth * speed + $80) >> 8
* original scale relationship:
      object positioning uses depth high byte
      Hawk model uses depth_hi >> 4
      Guardian/Creature models use depth_hi >> 2
* repeated web rings use the original $1177 vectors and depth high byte scale
* original 15-record $191C camera script retained

This remains a native port, not a Vectrex emulator. The remaining non-1:1
portion is mostly $08CF's direct VIA beam timing / exact longitudinal web draw,
some Guardian AI transitions, and exact sound synthesis.

Required:
  python3 + pygame
Files:
  Web Warp (1983).vec
  web_warp_vectors.json
  Vectrex BIOS (1982)(5).vec    (recommended; embedded table fallback exists)

Controls:
  Left/Right      move continuously across Web of Fantasy
  Up/Down         speed
  Space or 4      fire
  C or 3          Capture Rod
  1/Z, 2/X        Vectrex buttons 1/2
  F1              debug
  F2              original Trophy Room bug / fixed
  P               pause
  R               restart after game over
  Esc             quit
"""

from __future__ import annotations

import argparse
import json
import math
import random
from dataclasses import dataclass
from pathlib import Path

pygame = None


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

def require_pygame():
    global pygame
    if pygame is not None:
        return
    try:
        import pygame as _pg
    except ImportError:
        print("pygame is required to PLAY.")
        print("Recommended:")
        print("  python3 -m venv .venv")
        print("  source .venv/bin/activate")
        print("  python -m pip install pygame")
        raise SystemExit(1)
    pygame = _pg


W, H = 720, 960
CX, CY = W // 2, H // 2
FPS = 60

START_LIVES = 5
SHOT_COUNT = 9
GUARDIAN_COUNT = 6

SHOT_COOLDOWN = 8
CAPTURE_ROD_FRAMES = 0x0D
PLAYER_DEATH_FRAMES = 0x30
GUARDIAN_DEATH_FRAMES = 0x10

# IMPORTANT: there is no Vectrex pixel resolution. This factor is only the
# final analogue-beam -> desktop-raster calibration.
#
# V6 incorrectly multiplied 1/64 by 720/960 when switching to portrait. That
# shrank the physical beam a second time. Keep the Vectrex mapping independent
# of window-history and apply optional analogue gain only at the final stage.
BASE_HW_TO_PIXELS = 1.0 / 64.0
HW_TO_PIXELS = BASE_HW_TO_PIXELS

BLACK = (0, 0, 0)
FAINT = (54, 54, 54)
DIM = (100, 100, 100)
MID = (170, 170, 170)
WHITE = (238, 238, 238)


# ---------------------------------------------------------------------------
# 6809-width helpers
# ---------------------------------------------------------------------------

def u8(v): return v & 0xFF


def s8(v):
    v &= 0xFF
    return v - 0x100 if v & 0x80 else v


def u16(v): return v & 0xFFFF


def s16(v):
    v &= 0xFFFF
    return v - 0x10000 if v & 0x8000 else v


def hi(v): return (v >> 8) & 0xFF


def lo(v): return v & 0xFF


def clamp(v, a, b): return max(a, min(b, v))


def be16(buf, p):
    return (buf[p] << 8) | buf[p + 1]


def be16s(buf, p):
    return int.from_bytes(buf[p:p + 2], "big", signed=True)


def bcd_word(buf, p):
    v = be16(buf, p)
    ds = [(v >> 12) & 15, (v >> 8) & 15, (v >> 4) & 15, v & 15]
    return ds[0] * 1000 + ds[1] * 100 + ds[2] * 10 + ds[3]


def read80(buf, p):
    out = []
    while p < len(buf):
        c = buf[p]
        p += 1
        if c == 0x80:
            break
        out.append(chr(c) if 32 <= c < 127 else " ")
    return "".join(out), p


def neg16(v):
    return u16(-s16(v))


def signed_add16(a, b):
    return u16(s16(a) + s16(b))


def asr8(v):
    """6809 ASR on one byte -> (result, carry)."""
    v = u8(v)
    c = v & 1
    return ((v >> 1) | (v & 0x80)), c


def ror8(v, carry):
    """6809 ROR byte -> (result, carry)."""
    v = u8(v)
    nc = v & 1
    return ((v >> 1) | (0x80 if carry else 0)), nc


def asr16(v):
    """6809 arithmetic right shift of D implemented as ASRA / RORB."""
    A = hi(v)
    B = lo(v)
    A, c = asr8(A)
    B, _ = ror8(B, c)
    return (A << 8) | B


def sub8(a, b):
    # 6809 subtraction; carry represents borrow.
    a, b = u8(a), u8(b)
    r = a - b
    return u8(r), 1 if r < 0 else 0


def add8(a, b, carry=0):
    r = u8(a) + u8(b) + (1 if carry else 0)
    return u8(r), 1 if r > 0xFF else 0


def advance_depth(depth, speed, subtract=False):
    """
    ROM $0976/$0979.

    The 6809 computes the low-byte product first; MUL places bit 7 of the low
    product into Carry and ADCA #0 rounds the high part. Equivalent:
        delta = (depth * speed + $80) >> 8
    """
    depth &= 0xFFFF
    speed &= 0xFF
    delta = ((depth * speed) + 0x80) >> 8
    return u16(depth - delta if subtract else depth + delta)


# ---------------------------------------------------------------------------
# Original ROM + BIOS assets
# ---------------------------------------------------------------------------

class Assets:
    FALLBACK_ROTATION_TABLE = [
        0, 25, 50, 74, 98, 121, 142, 162,
        181, 198, 213, 226, 237, 245, 251, 255,
        255, 255, 251, 245, 237, 226, 213, 198,
        181, 162, 142, 121, 98, 74, 50, 25,
    ]

    def __init__(self, rom_path: Path, vectors_path: Path, bios_path: Path | None):
        self.rom = rom_path.read_bytes()
        if len(self.rom) != 0x2000:
            raise ValueError(f"Expected 8192-byte Web Warp ROM, got {len(self.rom)}")

        self.vectors = json.loads(vectors_path.read_text(encoding="utf-8"))

        self.bios = None
        if bios_path is not None and bios_path.exists():
            b = bios_path.read_bytes()
            if len(b) == 0x1000:
                self.bios = b

        if self.bios is not None:
            off = 0xFC6D - 0xF000
            self.rotation_table = list(self.bios[off:off + 32])
        else:
            self.rotation_table = list(self.FALLBACK_ROTATION_TABLE)

        self.copyright, p = read80(self.rom, 0)
        self.title_music = be16(self.rom, p)
        p += 6
        self.title, _ = read80(self.rom, p)
        self.title = self.title.strip()

        self.score_guardian = bcd_word(self.rom, 0x1163)
        self.score_capture = bcd_word(self.rom, 0x1165)
        self.score_trophy = bcd_word(self.rom, 0x1167)

        self.web_delay = list(self.rom[0x118F:0x11A9])
        self.player_angles = [s8(x) for x in self.rom[0x18BB:0x18C2]]

        self.bonus = []
        p = 0x18F2
        for _ in range(6):
            t, p = read80(self.rom, p)
            try:
                self.bonus.append(int(t.strip()))
            except ValueError:
                pass

        # $191C: duration, dA, dB, dWeb
        self.web_script = []
        p = 0x191C
        while p + 6 < len(self.rom):
            duration = self.rom[p]
            if duration == 0:
                break
            self.web_script.append((
                duration,
                be16s(self.rom, p + 1),
                be16s(self.rom, p + 3),
                be16s(self.rom, p + 5),
            ))
            p += 7

        self.trophy_keys = {}
        for key in self.vectors:
            if "_trophy_" in key and "_frame_" in key:
                tail = key.split("_trophy_", 1)[1]
                species = int(tail.split("_frame_", 1)[0])
                frame = int(tail.split("_frame_", 1)[1])
                self.trophy_keys[(species, frame)] = key

        self.player_keys = [
            "1996_player_frame_ptrslot_0",
            "19DC_player_frame_ptrslot_1",
            "1A22_player_frame_ptrslot_2",
            "1A68_player_frame_ptrslot_3",
        ]
        self.dragon_keys = [
            "1ABE_dragon_frame_ptrslot_0",
            "1B01_dragon_frame_ptrslot_1",
            "1B44_dragon_frame_ptrslot_2",
            "1B87_dragon_frame_ptrslot_3",
        ]

        self.build_web_tables()

    def vector(self, key):
        return self.vectors[key]["commands"]

    def trophy(self, species, frame):
        return self.vector(self.trophy_keys[(species % 20, frame & 1)])

    def player(self, frame):
        seq = [0, 1, 2, 3, 2, 1, 0, 0]
        return self.vector(self.player_keys[seq[frame & 7]])

    def dragon(self, frame):
        seq = [0, 1, 2, 3, 2, 1, 0, 0]
        return self.vector(self.dragon_keys[seq[frame & 7]])

    def build_web_tables(self):
        """
        Reconstructs what the ROM builds at:
          CA99 : 8 cumulative (Y,X) 16-bit web vertices
          CA43 : 7 segment vectors * 8
          CA60 : 7 segment vectors * 16
          CA7D : 7 segment vectors * 32
        """
        cmds = self.vector("1177_web_semicircle")

        # First mode record is a MOVE from origin to the first web vertex.
        first = cmds[0]
        y = s8(first["dy"]) << 8
        x = s8(first["dx"]) << 8
        self.vertex_words = [(u16(y), u16(x))]

        draw_deltas = []
        for c in cmds[1:]:
            if not c.get("draw"):
                continue
            dy = s8(c["dy"])
            dx = s8(c["dx"])
            draw_deltas.append((dy, dx))
            y = s16(y + (dy << 8))
            x = s16(x + (dx << 8))
            self.vertex_words.append((u16(y), u16(x)))

        if len(self.vertex_words) != 8 or len(draw_deltas) != 7:
            raise ValueError("Unexpected $1177 Web vector structure")

        self.motion8 = [(u16(dy * 8), u16(dx * 8)) for dy, dx in draw_deltas]
        self.motion16 = [(u16(dy * 16), u16(dx * 16)) for dy, dx in draw_deltas]
        self.motion32 = [(u16(dy * 32), u16(dx * 32)) for dy, dx in draw_deltas]

    def midpoint(self, segment):
        """
        Cartridge $0362 semantics:
          D = endpoint A ; ASRA ; RORB
          push D
          D = endpoint B ; ASRA ; RORB
          ADDD pushed
        i.e. halve EACH signed 16-bit endpoint first, then add.
        """
        a = self.vertex_words[segment]
        b = self.vertex_words[segment + 1]
        return (
            u16(asr16(a[0]) + asr16(b[0])),
            u16(asr16(a[1]) + asr16(b[1])),
        )


# ---------------------------------------------------------------------------
# Exact BIOS rise/run transformation
# ---------------------------------------------------------------------------

class BiosMath:
    def __init__(self, assets: Assets):
        self.tbl = assets.rotation_table

    def get_run_idx(self, angle):
        """
        BIOS F5DB.
        Returns (multiplier, flag).
        """
        a = u8(angle)
        b = 0x80 if (a & 0x20) else 0x00
        idx = a & 0x1F
        if idx == 0x10:
            b = u8(b + 1)
        return self.tbl[idx], b

    def get_rise_idx(self, angle):
        """BIOS F5D9: ADDA #$10 then falls into Get_Run_Idx."""
        return self.get_run_idx(u8(angle + 0x10))

    @staticmethod
    def xform(value, pair):
        """
        BIOS F665 core used by Xform_Run_a / Xform_Rise_a.

        The special flag bit 0 handles the exact +/-1.0 quadrant and avoids
        multiplying by 255. Otherwise use 8x8 MUL with the BIOS's rounding.
        """
        mult, flag = pair
        v = s8(value)

        if flag & 1:
            out = v
            if flag & 0x80:
                out = -out
            return s8(out)

        work_flag = flag
        mag = v
        if mag < 0:
            work_flag = u8(~work_flag)
            mag = -mag
            if mag > 127:
                mag = 128

        prod = (mult * (mag & 0xFF)) & 0xFFFF
        # 6809 MUL: C becomes bit 7 of low result; ADCA #0 performs rounding.
        out = ((prod >> 8) + (1 if (prod & 0x80) else 0)) & 0xFF

        if work_flag & 0x80:
            out = u8(-out)

        return s8(out)

    def transform_pair(self, y, x, angle):
        """
        Web Warp $0CC0:
          outY = Xform_Rise(y) + Xform_Run(x)
          outX = Xform_Rise(x) - Xform_Run(y)
        All outputs are 8-bit signed.
        """
        run = self.get_run_idx(angle)
        rise = self.get_rise_idx(angle)

        oy = s8(self.xform(y, rise) + self.xform(x, run))
        ox = s8(self.xform(x, rise) - self.xform(y, run))
        return oy, ox

    def rotate_delta(self, dy, dx, angle):
        return self.transform_pair(s8(dy), s8(dx), angle)


# ---------------------------------------------------------------------------
# $094F BuildDrawDisplacement
# ---------------------------------------------------------------------------

def build_draw_displacement(camera_a_hi, camera_b_hi, transformed_y, transformed_x):
    """
    Byte-exact transcription of cartridge $094F.

    IMPORTANT:
    The routine uses ASRA on A and ASRB on B separately. It does NOT perform
    a 16-bit ASRA/RORB shift here.

    Returns the two relative (dy,dx) vectors consumed by two Mov_Draw_VL calls.
    """
    ca = u8(camera_a_hi)
    cb = u8(camera_b_hi)
    A = u8(transformed_y)
    B = u8(transformed_x)

    # lda C8A0 / asra
    u0, _ = asr8(ca)
    # ldb C8A2 / asrb
    u1, _ = asr8(cb)

    # std ,u ; suba C8A0 ; subb C8A2 ; std 2,u
    u2, _ = sub8(u0, ca)
    u3, _ = sub8(u1, cb)

    # ldd transformed ; asra ; asrb ; suba ,u ; subb 1,u
    ah, _ = asr8(A)
    bh, _ = asr8(B)
    p1a, _ = sub8(ah, u0)
    p1b, _ = sub8(bh, u1)

    # reload transformed
    # asra ; adca 2,u  -- carry is bit shifted out by ASRA
    ah, carry_a = asr8(A)
    p2a, _ = add8(ah, u2, carry_a)

    # asrb ; adcb 3,u  -- ASRB establishes a NEW carry
    bh, carry_b = asr8(B)
    p2b, _ = add8(bh, u3, carry_b)

    return (s8(p1a), s8(p1b)), (s8(p2a), s8(p2b))



# ---------------------------------------------------------------------------
# Vector renderer
# ---------------------------------------------------------------------------

class Renderer:
    def __init__(self, surface, biosmath: BiosMath):
        self.s = surface
        self.bm = biosmath

    def line(self, a, b, color=MID, width=1):
        # clipline prevents enormous off-screen coordinates from making SDL's
        # rasterizer unnecessarily expensive and also makes window close robust.
        try:
            ax, ay = float(a[0]), float(a[1])
            bx, by = float(b[0]), float(b[1])
        except (TypeError, ValueError, OverflowError):
            return

        if not all(math.isfinite(v) for v in (ax, ay, bx, by)):
            return

        # Hard sanity guard before integer conversion.
        lim = 1_000_000
        if any(abs(v) > lim for v in (ax, ay, bx, by)):
            return

        clipped = self.s.get_rect().clipline(
            (int(round(ax)), int(round(ay))),
            (int(round(bx)), int(round(by))),
        )
        if clipped:
            if width == 1:
                pygame.draw.aaline(self.s, color, clipped[0], clipped[1], True)
            else:
                pygame.draw.line(self.s, color, clipped[0], clipped[1], width)

    def text(self, font, text, pos, color=MID, center=False):
        img = font.render(text, True, color)
        if center:
            pos = (
                int(pos[0] - img.get_width() / 2),
                int(pos[1] - img.get_height() / 2),
            )
        self.s.blit(img, pos)

    @staticmethod
    def hw_delta(dy, dx, scale):
        """
        Relative Vectrex beam delta -> desktop pixels.
        """
        px = dx * scale * HW_TO_PIXELS
        py = -dy * scale * HW_TO_PIXELS
        return px, py

    def move_pair(self, origin, pair, scale):
        dy, dx = pair
        px, py = self.hw_delta(dy, dx, scale)
        return origin[0] + px, origin[1] + py

    def original_mode_list(self, cmds, origin, scale, angle=0, color=WHITE):
        """
        Render a decoded Web Warp mode list using BIOS-style integer rotation.

        The ROM's vector data are dy/dx relative bytes. Every delta is transformed
        through the same rise/run integer path used by Rot_VL_Mode.
        """
        pos = (float(origin[0]), float(origin[1]))

        for c in cmds:
            dy = s8(c["dy"])
            dx = s8(c["dx"])
            if angle:
                dy, dx = self.bm.rotate_delta(dy, dx, angle)

            nxt = self.move_pair(pos, (dy, dx), scale)
            if c.get("draw"):
                self.line(
                    (int(round(pos[0])), int(round(pos[1]))),
                    (int(round(nxt[0])), int(round(nxt[1]))),
                    color
                )
            pos = nxt

        return pos


# ---------------------------------------------------------------------------
# World entities
# ---------------------------------------------------------------------------

@dataclass
class MovingEntity:
    active: bool = False
    state: int = 0

    depth: int = 0x0280

    # Equivalent to object offsets +3/+5.
    world_y: int = 0
    world_x: int = 0

    # Equivalent to +0D/+0E/+0F movement state.
    direction_index: int = 0x0C   # segment * 4
    subindex: int = 0
    direction: int = 1

    phase: int = 0

    @property
    def segment(self):
        return clamp(self.direction_index >> 2, 0, 6)


@dataclass
class Shot:
    active: bool = False
    depth: int = 0xE000
    world_y: int = 0
    world_x: int = 0


@dataclass
class PlayerState:
    lives: int = START_LIVES
    score: int = 0
    trophies: int = 0
    next_bonus: int = 0


# ---------------------------------------------------------------------------
# Game
# ---------------------------------------------------------------------------

class Game:
    def __init__(self, assets: Assets):
        self.a = assets
        self.bm = BiosMath(assets)
        self.rng = random.Random(0x1983)

        self.state = "TITLE"
        self.num_players = 1
        self.players = [PlayerState(), PlayerState()]
        self.player_index = 0

        self.hawk = MovingEntity()
        self.hawk_fire_cd = 0
        self.hawk_rod_timer = 0
        self.hawk_death_timer = 0
        self.hawk_state = 1
        self.speed = 4

        self.guardians = [MovingEntity() for _ in range(GUARDIAN_COUNT)]
        self.creature = MovingEntity()
        self.creature_species = 0
        self.creature_captured = False
        self.portal = MovingEntity()
        self.dragon = MovingEntity()
        self.dragon_shot = Shot()

        self.shots = [Shot() for _ in range(SHOT_COUNT)]

        # 1 initial + 8 free-list web-line records.
        self.web_lines = [{"active": False, "depth": 0x0280} for _ in range(9)]
        self.web_spawn_timer = 0

        # $191C motion state.
        self.web_script_i = 0
        self.web_script_timer = 1
        self.camera_a = 0
        self.camera_b = 0
        self.web_angle_word = 0

        self.failed_sequence_count = 0

        self.frame = 0
        self.paused = False
        self.debug = False
        self.original_trophy_bug = True
        self.message = ""
        self.message_timer = 0
        self.trophy_timer = 0

        self.reset_round()

    @property
    def p(self):
        return self.players[self.player_index]

    # ------------------------------------------------------------------
    # Table helpers
    # ------------------------------------------------------------------

    def motion_table(self, steps):
        if steps == 32:
            return self.a.motion8
        if steps == 16:
            return self.a.motion16
        if steps == 8:
            return self.a.motion32
        raise ValueError(steps)

    def place_mid_segment(self, entity, segment, steps):
        entity.direction_index = segment * 4
        entity.subindex = steps // 2
        entity.world_y, entity.world_x = self.a.midpoint(segment)
        entity.direction = 1

    def place_vertex(self, entity, vertex):
        vertex = clamp(vertex, 0, 7)
        y, x = self.a.vertex_words[vertex]
        entity.world_y = y
        entity.world_x = x
        if vertex >= 7:
            entity.direction_index = 6 * 4
            entity.subindex = 32
        else:
            entity.direction_index = vertex * 4
            entity.subindex = 0

    def move_entity_along_web(self, e: MovingEntity, request_dir: int, steps: int):
        """
        Native transcription of the central behavior of cartridge $0C15.

        request_dir:
          +1 -> progress through the $1177 segment order (visually leftward)
          -1 -> reverse

        The original subindex ranges:
           Hawk      0..32
           Guardian  0..16
           Creature  0..8
        """
        if request_dir == 0:
            return

        request_dir = 1 if request_dir > 0 else -1
        e.direction = request_dir

        seg = e.segment
        candidate = e.subindex + request_dir
        table = self.motion_table(steps)

        if candidate > steps:
            # Cross into next segment.
            if seg >= 6:
                e.subindex = steps
                return
            seg += 1
            e.direction_index = seg * 4
            e.subindex = 0
            e.world_y, e.world_x = self.a.vertex_words[seg]
        elif candidate < 0:
            # Cross into previous segment.
            if seg <= 0:
                e.subindex = 0
                return
            # Shared vertex is the old segment's starting vertex.
            shared_vertex = seg
            seg -= 1
            e.direction_index = seg * 4
            e.subindex = steps
            e.world_y, e.world_x = self.a.vertex_words[shared_vertex]
        else:
            e.subindex = candidate

        seg = e.segment
        dy, dx = table[seg]

        if request_dir < 0:
            dy = neg16(dy)
            dx = neg16(dx)

        e.world_y = u16(e.world_y + dy)
        e.world_x = u16(e.world_x + dx)

    # ------------------------------------------------------------------
    # Session / round
    # ------------------------------------------------------------------

    def reset_session(self, players):
        self.num_players = players
        self.players = [PlayerState(), PlayerState()]
        self.player_index = 0
        self.failed_sequence_count = 0
        self.state = "PLAY"
        self.reset_round()

    def reset_round(self):
        self.hawk = MovingEntity(active=True, state=1, depth=0xE000)
        self.place_mid_segment(self.hawk, 3, 32)

        self.hawk_state = 1
        self.hawk_fire_cd = SHOT_COOLDOWN
        self.hawk_rod_timer = 0
        self.hawk_death_timer = 0
        self.speed = 4

        self.guardians = [MovingEntity() for _ in range(GUARDIAN_COUNT)]
        for _ in range(clamp(2 + (self.p.trophies & 0x7F) // 3, 2, 6)):
            self.spawn_guardian()

        self.creature = MovingEntity(active=True, state=1, depth=0x0280)
        seg = self.rng.randrange(7)
        self.place_mid_segment(self.creature, seg, 8)
        self.creature_species = (self.p.trophies & 0x7F) % 20
        self.creature_captured = False

        self.portal = MovingEntity()
        self.dragon = MovingEntity()
        self.dragon_shot = Shot()
        self.shots = [Shot() for _ in range(SHOT_COUNT)]

        self.web_lines = [{"active": False, "depth": 0x0280} for _ in range(9)]
        self.web_lines[0]["active"] = True
        self.web_spawn_timer = self.current_web_delay()

        # $106A explicitly clears A0/A2 then starts $191C.
        self.camera_a = 0
        self.camera_b = 0
        self.web_angle_word = 0
        self.web_script_i = 0
        self.web_script_timer = self.a.web_script[0][0] if self.a.web_script else 1

        # Original $0239 does not enter gameplay with a single ring. It repeatedly
        # advances/spawns the 3-byte web-line records until the oldest one passes
        # the $E0 depth threshold. Reproduce that startup fill now.
        self.prefill_web_lines()

    # ------------------------------------------------------------------
    # Exact BIOS-derived projection
    # ------------------------------------------------------------------

    def camera_angle_byte(self):
        # TransformAllWorldCoordinates loads direct byte C8B5.
        return hi(self.web_angle_word)

    def player_model_angle_byte(self):
        # WW_UpdatePlayerAngle: table[directionIndex>>2] + byte C8B5.
        base = self.a.player_angles[self.hawk.segment]
        return u8(base + s8(self.camera_angle_byte()))

    def transform_world(self, e: MovingEntity):
        y = s8(hi(e.world_y))
        x = s8(hi(e.world_x))
        return self.bm.transform_pair(y, x, self.camera_angle_byte())

    def beam_move(self, pos, dy, dx, scale):
        """One native relative Vectrex move mapped into portrait pixels."""
        x, y = float(pos[0]), float(pos[1])
        x += s8(dx) * int(scale) * HW_TO_PIXELS
        y -= s8(dy) * int(scale) * HW_TO_PIXELS
        return x, y

    def camera_pre_move(self, pos=(CX, CY)):
        """
        The renderer performs this BEFORE $094F:
          A = C8A0
          B = C8A2
          scale = $7F
          start timer
        It was missing entirely in V4/V5.
        """
        return self.beam_move(
            pos,
            s8(hi(self.camera_a)),
            s8(hi(self.camera_b)),
            0x7F,
        )

    def object_origin(self, e: MovingEntity):
        """
        Original object positioning order:
          Reset0Ref
          camera pre-move (C8A0,C8A2) @ scale $7F
          transform world high bytes via BIOS Rise/Run
          $094F -> two relative vectors
          Mov_Draw_VL twice @ scale depth_hi
        """
        ty, tx = self.transform_world(e)

        p1, p2 = build_draw_displacement(
            hi(self.camera_a),
            hi(self.camera_b),
            ty,
            tx,
        )

        pos = self.camera_pre_move((CX, CY))
        scale = hi(e.depth)
        pos = self.beam_move(pos, p1[0], p1[1], scale)
        pos = self.beam_move(pos, p2[0], p2[1], scale)

        return pos, (ty, tx), (p1, p2)


    # ------------------------------------------------------------------
    # Web camera script
    # ------------------------------------------------------------------

    def update_web_script(self):
        if not self.a.web_script:
            return

        duration, da, db, dw = self.a.web_script[self.web_script_i]

        self.camera_a = u16(self.camera_a + da)
        self.camera_b = u16(self.camera_b + db)

        # Exact interesting part of $1094:
        # LDD 5,X ; ADDD <B5 ; ASRA ; ASRA ; bounds ; STD <B5
        summed = u16(self.web_angle_word + dw)
        A = hi(summed)
        B = lo(summed)
        A, _ = asr8(A)
        A, _ = asr8(A)
        candidate = (A << 8) | B

        # The cartridge's signed branch pair implements a bounded accepted
        # range. This retains the actual shifted word when it falls in the
        # observed legal angle band.
        if -11 <= s8(A) <= 11:
            self.web_angle_word = candidate

        self.web_script_timer -= 1
        if self.web_script_timer <= 0:
            self.web_script_i += 1
            if self.web_script_i >= len(self.a.web_script):
                self.web_script_i = 0
            self.web_script_timer = self.a.web_script[self.web_script_i][0]

    # ------------------------------------------------------------------
    # Web line pool
    # ------------------------------------------------------------------

    def prefill_web_lines(self):
        """
        Reproduce cartridge $0239's pre-game web fill.

        Each pass:
          - advance every active 3-byte record via $0976
          - if an active record crosses depth high > $E0: free it and START game
          - otherwise execute the equivalent of $0F54 spawn countdown/allocation
        """
        # Keep the initial record; clear the 8 free records.
        for i, rec in enumerate(self.web_lines):
            rec["active"] = (i == 0)
            rec["depth"] = 0x0280

        self.web_spawn_timer = self.current_web_delay()

        # Original free-list is stack-like. Record identity does not affect
        # geometry, but LIFO order is retained for deterministic debugging.
        free_slots = list(range(8, 0, -1))

        for _tick in range(20000):
            crossed = False

            for i, rec in enumerate(self.web_lines):
                if not rec["active"]:
                    continue

                rec["depth"] = advance_depth(rec["depth"], self.speed, False)

                if hi(rec["depth"]) > 0xE0:
                    rec["active"] = False
                    if i != 0 and i not in free_slots:
                        free_slots.append(i)
                    crossed = True
                    break

            if crossed:
                return

            if self.web_spawn_timer:
                self.web_spawn_timer -= 1
            else:
                if free_slots:
                    i = free_slots.pop()
                    self.web_lines[i]["active"] = True
                    self.web_lines[i]["depth"] = 0x0280
                self.web_spawn_timer = self.current_web_delay()

        raise RuntimeError("web prefill failed to reach $E0 threshold")

    def current_web_delay(self):
        """
        Exact ROM indexing:
          LDX #table_delays_between_web_lines-1
          LDB A,X
        and during speed changes:
          DECA
          LDA A,U

        Therefore speed 1 -> table[0], speed 4 -> table[3] == $2A.
        """
        if self.speed <= 0:
            # Speed zero is not used as a normal lookup index by the cartridge;
            # retain the longest practical delay for native keyboard control.
            return self.a.web_delay[0]
        i = clamp(self.speed - 1, 0, len(self.a.web_delay) - 1)
        v = self.a.web_delay[i]
        return 1 if v == 0 else v

    def update_web_lines(self):
        for rec in self.web_lines:
            if not rec["active"]:
                continue
            rec["depth"] = advance_depth(rec["depth"], self.speed, False)
            if hi(rec["depth"]) > 0xE0:
                rec["active"] = False

        if self.web_spawn_timer:
            self.web_spawn_timer -= 1
        else:
            for rec in self.web_lines[1:]:
                if not rec["active"]:
                    rec["active"] = True
                    rec["depth"] = 0x0280
                    break
            self.web_spawn_timer = self.current_web_delay()

    # ------------------------------------------------------------------
    # Entities
    # ------------------------------------------------------------------

    def spawn_guardian(self):
        for g in self.guardians:
            if not g.active and g.state == 0:
                g.active = True
                g.state = 1
                g.depth = 0x0280
                seg = self.rng.randrange(7)
                self.place_mid_segment(g, seg, 16)
                g.direction = self.rng.choice((-1, 1))
                g.phase = self.rng.randrange(256)
                return True
        return False

    def fire(self):
        if self.state != "PLAY" or self.hawk_state <= 0 or self.hawk_fire_cd:
            return
        for s in self.shots:
            if not s.active:
                s.active = True
                s.depth = self.hawk.depth
                s.world_y = self.hawk.world_y
                s.world_x = self.hawk.world_x
                self.hawk_fire_cd = SHOT_COOLDOWN
                return

    def activate_rod(self):
        if self.state == "PLAY" and self.hawk_state > 0:
            self.hawk_rod_timer = CAPTURE_ROD_FRAMES

    def update_shots(self):
        for s in self.shots:
            if not s.active:
                continue
            # Renderer uses a separate scale byte around $10 for shot radial
            # movement; preserve the same multiplicative direction.
            s.depth = advance_depth(s.depth, 0x10, True)
            if s.depth <= 0x0500:
                s.active = False

    def update_guardians(self):
        for g in self.guardians:
            if g.state < 0:
                g.state += 1
                if g.state == 0:
                    g.active = False
                continue
            if not g.active:
                continue

            g.phase = u8(g.phase + 1)

            # Guardian radial/depth movement uses current speed in the normal
            # forward state.
            g.depth = advance_depth(g.depth, self.speed, False)

            # The original AI changes segment motion in discrete signed steps.
            # Exact decision timing is one of the remaining unfinished labels;
            # movement itself is now the real CA60 16-step table.
            if (g.phase & 0x07) == 0:
                if self.rng.random() < 0.35:
                    if g.segment in (0, 6):
                        g.direction = -g.direction
                    self.move_entity_along_web(g, g.direction, 16)

            if hi(g.depth) > 0xE0:
                # Player/entity collision threshold later uses three axes.
                if self.entity_near_player(g, 12, 8):
                    g.state = -GUARDIAN_DEATH_FRAMES
                    self.kill_hawk()
                else:
                    # Passed Guardian: return from behind.
                    g.depth = 0xE000
                    g.direction = -g.direction

    def update_creature(self):
        if not self.creature.active:
            return

        self.creature.depth = advance_depth(self.creature.depth, self.speed, False)
        if self.frame % 6 == 0:
            d = self.rng.choice((-1, 0, 0, 1))
            if d:
                self.move_entity_along_web(self.creature, d, 8)

        if hi(self.creature.depth) > 0xE0:
            if self.entity_near_player(self.creature, 12, 8):
                self.failed_sequence_count += 1
                self.kill_hawk()
            self.creature.depth = 0x0280

    def entity_near_player(self, e, depth_threshold, coord_threshold):
        """
        Approximate the ROM's 3-axis comparisons using the exact world words.
        The high-byte comparisons are now in the original coordinate domain.
        """
        if abs(s8(hi(e.depth)) - s8(hi(self.hawk.depth))) > depth_threshold:
            return False
        if abs(s8(hi(e.world_y)) - s8(hi(self.hawk.world_y))) > coord_threshold:
            return False
        if abs(s8(hi(e.world_x)) - s8(hi(self.hawk.world_x))) > coord_threshold:
            return False
        return True

    def capture_test(self):
        if self.hawk_rod_timer <= 0 or not self.creature.active:
            return

        # $0FCE first checks depth byte <= $18 then BIOS Obj_Hit(16,8).
        if abs(hi(self.hawk.depth) - hi(self.creature.depth)) <= 0x18:
            if (
                abs(s8(hi(self.creature.world_y)) - s8(hi(self.hawk.world_y))) <= 16
                and
                abs(s8(hi(self.creature.world_x)) - s8(hi(self.hawk.world_x))) <= 8
            ):
                self.creature.active = False
                self.creature_captured = True
                self.p.score += self.a.score_capture
                self.hawk_rod_timer = 0
                self.message = f"CAPTURE +{self.a.score_capture}"
                self.message_timer = 60

    def spawn_portal_if_ready(self):
        if not self.creature_captured or self.portal.active:
            return
        if any(g.active and g.state > 0 for g in self.guardians):
            return

        # $10A9 selects one of the 8 CA99 vertices and copies those exact words.
        vertex = self.rng.randrange(8)
        self.portal = MovingEntity(active=True, state=1, depth=0x0280)
        self.place_vertex(self.portal, vertex)

    def update_portal(self):
        if not self.portal.active:
            return

        self.portal.depth = advance_depth(self.portal.depth, self.speed, False)
        if hi(self.portal.depth) > 0xE0:
            if (
                abs(s8(hi(self.portal.world_y)) - s8(hi(self.hawk.world_y))) <= 8
                and
                abs(s8(hi(self.portal.world_x)) - s8(hi(self.hawk.world_x))) <= 8
            ):
                self.portal.active = False
                self.creature_captured = False
                self.p.score += self.a.score_trophy
                self.p.trophies += 1

                threshold = 0x20 if self.original_trophy_bug else 20
                if 0 <= self.p.trophies and self.p.trophies > threshold:
                    self.p.trophies = 0x80

                self.state = "TROPHY"
                self.trophy_timer = 6 * 256
                self.failed_sequence_count = 0
            else:
                self.portal.active = False
                self.creature_captured = False
                self.creature.active = True
                self.creature.depth = 0x0280
                self.failed_sequence_count += 1

    def update_dragon(self):
        if self.failed_sequence_count >= 2 and not self.dragon.active:
            self.dragon = MovingEntity(active=True, state=2, depth=0x0280)
            self.place_mid_segment(self.dragon, 3, 16)
            self.failed_sequence_count = 0

        if not self.dragon.active:
            return

        self.dragon.phase = u8(self.dragon.phase + 1)
        self.dragon.depth = advance_depth(
            self.dragon.depth,
            max(2, self.speed // 2),
            False
        )

        if hi(self.dragon.depth) > 0xA0:
            self.dragon.depth = 0x3000

        if not self.dragon_shot.active and self.dragon.phase % 90 == 0:
            self.dragon_shot.active = True
            self.dragon_shot.depth = 0xB000
            self.dragon_shot.world_y = self.hawk.world_y
            self.dragon_shot.world_x = self.hawk.world_x

        if self.dragon_shot.active:
            self.dragon_shot.depth = advance_depth(
                self.dragon_shot.depth, 0x10, False
            )
            if hi(self.dragon_shot.depth) >= hi(self.hawk.depth):
                # ROM Obj_Hit is 5x7.
                dy = abs(s8(hi(self.dragon_shot.world_y)) - s8(hi(self.hawk.world_y)))
                dx = abs(s8(hi(self.dragon_shot.world_x)) - s8(hi(self.hawk.world_x)))
                if dy <= 5 and dx <= 7:
                    self.kill_hawk()
                self.dragon_shot.active = False

    def shot_collisions(self):
        for g in self.guardians:
            if not g.active or g.state <= 0:
                continue
            for s in self.shots:
                if not s.active:
                    continue

                # Same coordinate domain as original threshold logic.
                dd = abs(hi(g.depth) - hi(s.depth))
                dy = abs(s8(hi(g.world_y)) - s8(hi(s.world_y)))
                dx = abs(s8(hi(g.world_x)) - s8(hi(s.world_x)))

                if dd <= 12 and dy <= 8 and dx <= 8:
                    g.state = -GUARDIAN_DEATH_FRAMES
                    s.active = False
                    self.p.score += self.a.score_guardian + self.speed
                    break

    def kill_hawk(self):
        if self.hawk_state > 0:
            self.hawk_state = -2
            self.hawk_death_timer = PLAYER_DEATH_FRAMES

    def finish_life(self):
        self.p.lives -= 1

        if self.p.lives <= 0:
            if self.num_players == 2:
                other = 1 - self.player_index
                if self.players[other].lives > 0:
                    self.player_index = other
                    self.reset_round()
                    return
            self.state = "GAMEOVER"
            return

        if self.num_players == 2:
            other = 1 - self.player_index
            if self.players[other].lives > 0:
                self.player_index = other

        self.reset_round()

    def bonus_check(self):
        while self.p.next_bonus < len(self.a.bonus):
            goal = self.a.bonus[self.p.next_bonus]
            if self.p.score < goal:
                break
            self.p.lives += 1
            self.p.next_bonus += 1
            self.message = f"BONUS LIFE {goal}"
            self.message_timer = 90

    # ------------------------------------------------------------------
    # Frame update
    # ------------------------------------------------------------------

    def update_play(self, keys):
        if self.hawk_state < 0:
            self.hawk_death_timer -= 1
            if self.hawk_death_timer <= 0:
                self.hawk_state = 0
                self.finish_life()
            return

        # The original analog threshold is > $10. A held keyboard direction is
        # treated as full analog input and therefore advances one substep/frame.
        if keys[pygame.K_LEFT]:
            self.move_entity_along_web(self.hawk, +1, 32)
        elif keys[pygame.K_RIGHT]:
            self.move_entity_along_web(self.hawk, -1, 32)

        # Speed is discrete 0..24 in the ROM table domain.
        if self.frame % 4 == 0:
            if keys[pygame.K_UP]:
                self.speed = min(24, self.speed + 1)
            if keys[pygame.K_DOWN]:
                self.speed = max(0, self.speed - 1)

        # Hawk radial depth update from joystick Y in the original is bounded
        # between high bytes $78 and $E0. Keyboard forward/back modifies it
        # modestly to retain those bounds.
        if keys[pygame.K_UP]:
            candidate = advance_depth(self.hawk.depth, 2, False)
            if 0x78 <= hi(candidate) <= 0xE0:
                self.hawk.depth = candidate
        elif keys[pygame.K_DOWN]:
            candidate = advance_depth(self.hawk.depth, 2, True)
            if 0x78 <= hi(candidate) <= 0xE0:
                self.hawk.depth = candidate

        if self.hawk_fire_cd:
            self.hawk_fire_cd -= 1
        if self.hawk_rod_timer:
            self.hawk_rod_timer -= 1

        # Preserve cartridge subsystem order as much as a native renderer allows.
        self.update_shots()
        self.update_guardians()
        self.update_dragon()
        self.update_web_lines()
        self.update_web_script()
        self.update_creature()
        self.capture_test()
        self.spawn_portal_if_ready()
        self.update_portal()
        self.shot_collisions()
        self.bonus_check()

        if (
            not self.creature_captured
            and self.frame % max(65, 175 - (self.p.trophies & 0x7F) * 3) == 0
        ):
            self.spawn_guardian()

    def update(self, keys):
        self.frame += 1

        if self.message_timer:
            self.message_timer -= 1
            if not self.message_timer:
                self.message = ""

        if self.paused:
            return

        if self.state == "PLAY":
            self.update_play(keys)
        elif self.state == "TROPHY":
            self.trophy_timer -= 1
            if self.trophy_timer <= 0:
                self.state = "PLAY"
                self.reset_round()

    # ------------------------------------------------------------------
    # Input
    # ------------------------------------------------------------------

    def handle_event(self, ev):
        if ev.type != pygame.KEYDOWN:
            return True

        if ev.key == pygame.K_ESCAPE:
            return False
        if ev.key == pygame.K_F1:
            self.debug = not self.debug
        if ev.key == pygame.K_F2:
            self.original_trophy_bug = not self.original_trophy_bug
            self.message = (
                "TROPHY BUG: ORIGINAL $20"
                if self.original_trophy_bug
                else "TROPHY BUG: FIXED 20"
            )
            self.message_timer = 80
        if ev.key == pygame.K_p:
            self.paused = not self.paused

        if self.state == "TITLE":
            if ev.key in (pygame.K_SPACE, pygame.K_4):
                self.state = "SELECT"

        elif self.state == "SELECT":
            if ev.key in (pygame.K_1, pygame.K_z):
                self.reset_session(1)
            elif ev.key in (pygame.K_2, pygame.K_x):
                self.reset_session(2)

        elif self.state == "PLAY":
            if ev.key in (pygame.K_SPACE, pygame.K_4):
                self.fire()
            elif ev.key in (pygame.K_c, pygame.K_3):
                self.activate_rod()

        elif self.state == "TROPHY":
            if ev.key in (
                pygame.K_1, pygame.K_z,
                pygame.K_2, pygame.K_x,
                pygame.K_SPACE
            ):
                self.state = "PLAY"
                self.reset_round()

        elif self.state == "GAMEOVER":
            if ev.key in (pygame.K_r, pygame.K_SPACE):
                self.state = "TITLE"

        return True

    # ------------------------------------------------------------------
    # Rendering helpers
    # ------------------------------------------------------------------

    def web_initial_vertex_displacement(self):
        """
        The copied $1177 list starts with:
            mode=$00, dy=$30, dx=$50
        But RAM_C887 points three bytes later, at the first DRAW record.

        Therefore the initial MOVE endpoint is transformed separately and used
        to build the two C92F positioning vectors via $094F.
        """
        first = self.a.vector("1177_web_semicircle")[0]
        ty, tx = self.bm.transform_pair(
            s8(first["dy"]),
            s8(first["dx"]),
            self.camera_angle_byte(),
        )
        return build_draw_displacement(
            hi(self.camera_a),
            hi(self.camera_b),
            ty,
            tx,
        )

    def web_ring_origin(self, depth):
        """
        Exact high-level equivalent of:
          Reset0Ref
          camera pre-move @ $7F
          scale = depth_hi
          Mov_Draw_VL(C92F)
          Mov_Draw_VL(C931)
        """
        p1, p2 = self.web_initial_vertex_displacement()
        pos = self.camera_pre_move((CX, CY))
        scale = hi(depth)
        pos = self.beam_move(pos, p1[0], p1[1], scale)
        pos = self.beam_move(pos, p2[0], p2[1], scale)
        return pos

    def web_ring_points(self, depth):
        """
        Screen points of the seven DRAW records only.

        The first point is the separately positioned initial vertex. This is
        the structure used by the real ring Draw_VLp path.
        """
        cmds = self.a.vector("1177_web_semicircle")
        pos = self.web_ring_origin(depth)
        pts = [(int(round(pos[0])), int(round(pos[1])))]
        scale = hi(depth)
        angle = self.camera_angle_byte()

        for c in cmds[1:]:
            # cmds[1:] are the seven $FF draw records.
            dy = s8(c["dy"])
            dx = s8(c["dx"])
            dy, dx = self.bm.rotate_delta(dy, dx, angle)
            pos = self.beam_move(pos, dy, dx, scale)
            pts.append((int(round(pos[0])), int(round(pos[1]))))

        return pts

    def draw_web(self, r: Renderer):
        """
        Moving ring path reconstructed from $0634:

          camera pre-move (C8A0,C8A2) at scale $7F
          ring depth update via $0976
          scale = depth_hi
          two positioning moves from C92F
          Draw_VLp at RAM_C887 = transformed packet + 3

        Thus the $00,$30,$50 initial MOVE is NOT drawn/executed a second time.
        """
        rings = sorted(
            [rec for rec in self.web_lines if rec["active"]],
            key=lambda q: hi(q["depth"])
        )

        all_pts = []

        for rec in rings:
            scale = hi(rec["depth"])
            origin = self.web_ring_origin(rec["depth"])
            intensity = DIM if scale < 0x70 else MID

            # Draw only first-draw-record onward, matching C887 = buffer + 3.
            r.original_mode_list(
                self.a.vector("1177_web_semicircle")[1:],
                origin,
                scale,
                self.camera_angle_byte(),
                intensity,
            )

            all_pts.append(self.web_ring_points(rec["depth"]))

        # $08CF is the one remaining specialized beam path. Between ordinary
        # rings we can safely connect identical original $1177 vertices.
        for ring0, ring1 in zip(all_pts, all_pts[1:]):
            for p0, p1 in zip(ring0, ring1):
                r.line(p0, p1, FAINT)

        # ORIGINAL RENDERER FACT:
        # After the moving ring pool has been drawn, Web Warp performs a second
        # web pass and explicitly sets VIA scale to $E0 before calling $08CF.
        #
        # V7 omitted that entire foreground continuation, so the rails stopped
        # visibly at the nearest live ring. Until $08CF itself is fully emulated,
        # extend each exact rail from the nearest ring to the corresponding
        # fixed-$E0 endpoint. Do NOT draw another U cross-ring there.
        if all_pts:
            front_pts = self.web_ring_points(0xE000)
            nearest = all_pts[-1]
            for p0, p1 in zip(nearest, front_pts):
                r.line(p0, p1, MID)


    def draw_entity_model(
        self,
        r: Renderer,
        e: MovingEntity,
        commands,
        model_scale,
        model_angle=0,
        color=WHITE
    ):
        origin, _, _ = self.object_origin(e)
        r.original_mode_list(
            commands,
            origin,
            model_scale,
            model_angle,
            color
        )
        return origin

    def draw_hawk(self, r: Renderer):
        origin, _, _ = self.object_origin(self.hawk)

        if self.hawk_state < 0:
            r.original_mode_list(
                self.a.vector("112C_pattern_x_cross"),
                origin,
                max(4, hi(self.hawk.depth) >> 4),
                u8(self.frame * 2),
                WHITE
            )
            return

        # Exact renderer uses depth_hi >> 4 for Hawk's Draw_VLp scale.
        scale = max(1, hi(self.hawk.depth) >> 4)
        angle = self.player_model_angle_byte()

        r.original_mode_list(
            self.a.player((self.frame >> 1) & 7),
            origin,
            scale,
            angle,
            WHITE
        )

        if self.hawk_rod_timer:
            # Display rod from Hawk toward the creature's exact object origin.
            if self.creature.active:
                c_origin, _, _ = self.object_origin(self.creature)
                dx = c_origin[0] - origin[0]
                dy = c_origin[1] - origin[1]
                length = math.hypot(dx, dy)
                if length > 1:
                    factor = min(1.0, 115.0 / length)
                    q = (
                        int(origin[0] + dx * factor),
                        int(origin[1] + dy * factor),
                    )
                    r.line(
                        (int(origin[0]), int(origin[1])),
                        q,
                        WHITE
                    )

    def shot_origin(self, s: Shot):
        # Shots preserve the world position copied from Hawk and change only
        # their radial/depth word.
        tmp = MovingEntity(
            active=True,
            state=1,
            depth=s.depth,
            world_y=s.world_y,
            world_x=s.world_x,
        )
        return self.object_origin(tmp)[0]

    def draw_shots(self, r: Renderer):
        for s in self.shots:
            if not s.active:
                continue
            p = self.shot_origin(s)
            # ROM draws shot from its stored +3/+5 vector; use a short beam in
            # the transformed outward direction instead of a generic sprite.
            scale = max(1, hi(s.depth) >> 4)
            dy, dx = self.bm.transform_pair(8, 0, self.camera_angle_byte())
            qx = p[0] + dx * scale * HW_TO_PIXELS
            qy = p[1] - dy * scale * HW_TO_PIXELS
            r.line(
                (int(p[0]), int(p[1])),
                (int(qx), int(qy)),
                WHITE
            )

    def draw_guardians(self, r: Renderer):
        model = self.a.vector("11B9_guardian_drone")

        for g in self.guardians:
            if not g.active and g.state == 0:
                continue

            origin, _, _ = self.object_origin(g)
            scale = max(1, hi(g.depth) >> 2)

            if g.state < 0:
                r.original_mode_list(
                    self.a.vector("112C_pattern_x_cross"),
                    origin,
                    scale,
                    u8((GUARDIAN_DEATH_FRAMES + g.state) * 3),
                    WHITE
                )
            else:
                # The normal Drone renderer does not Rot_VL_Mode the mine list.
                r.original_mode_list(
                    model,
                    origin,
                    scale,
                    0,
                    MID
                )

    def draw_creature(self, r: Renderer):
        if not self.creature.active:
            return

        scale = max(1, hi(self.creature.depth) >> 2)
        self.draw_entity_model(
            r,
            self.creature,
            self.a.trophy(
                self.creature_species,
                (self.frame // 10) & 1
            ),
            scale,
            0,
            WHITE
        )

    def draw_portal(self, r: Renderer):
        if not self.portal.active:
            return

        # Portal draw path retains full depth scale around the two move calls.
        scale = max(1, hi(self.portal.depth) >> 1)
        self.draw_entity_model(
            r,
            self.portal,
            self.a.vector("111C_trophy_room_portal"),
            scale,
            0,
            WHITE
        )

    def draw_dragon(self, r: Renderer):
        if not self.dragon.active:
            return

        origin, _, _ = self.object_origin(self.dragon)
        scale = max(1, hi(self.dragon.depth) >> 2)

        # Dragon body is explicitly Rot_VL_Mode'd in the cartridge renderer.
        angle = u8(s8(self.camera_angle_byte()) + 8)

        r.original_mode_list(
            self.a.dragon((self.frame // 5) & 7),
            origin,
            scale,
            angle,
            MID
        )

        r.original_mode_list(
            self.a.vector("1BCA_dragon_head"),
            origin,
            max(1, scale - 1),
            u8(angle + s8((self.frame // 8) & 7) - 3),
            WHITE
        )

        if self.dragon_shot.active:
            p = self.shot_origin(self.dragon_shot)
            rr = max(2, hi(self.dragon_shot.depth) >> 5)
            r.line((int(p[0] - rr), int(p[1])), (int(p[0] + rr), int(p[1])), WHITE)
            r.line((int(p[0]), int(p[1] - rr)), (int(p[0]), int(p[1] + rr)), WHITE)

    # ------------------------------------------------------------------
    # Screens / HUD
    # ------------------------------------------------------------------

    def draw_title(self, r, big, mid, small, keys):
        r.text(small, "GCE 1983", (CX, 145), MID, True)
        r.text(big, self.a.title, (CX, 250), WHITE, True)
        r.text(mid, "PRESS 4 / SPACE", (CX, 350), MID, True)

        b1 = keys[pygame.K_1] or keys[pygame.K_z]
        b2 = keys[pygame.K_2] or keys[pygame.K_x]
        b4 = keys[pygame.K_4] or keys[pygame.K_SPACE]

        if b1 and b2 and b4:
            y = 520
            for line in (
                "PROGRAMMED BY",
                "WILLIAM HAWKINS",
                "DUNCAN MUIRHEAD",
                "PATRICK KING",
                "GT 1983",
            ):
                r.text(
                    mid if line == "PROGRAMMED BY" else small,
                    line,
                    (CX, y),
                    WHITE if line == "PROGRAMMED BY" else MID,
                    True
                )
                y += 38

    def draw_select(self, r, big, mid):
        r.text(big, "SELECT GAME", (CX, 220), WHITE, True)
        r.text(mid, "1   ONE PLAYER", (CX, 360), MID, True)
        r.text(mid, "2   TWO PLAYERS", (CX, 420), MID, True)

    def draw_hud(self, r, small):
        r.text(small, f"P{self.player_index + 1}  {self.p.score:06d}", (18, 18), WHITE)
        r.text(small, f"LIVES {self.p.lives}", (W - 150, 18), MID)
        r.text(small, f"SPEED {self.speed:03d}", (18, 48), MID)
        r.text(small, f"TROPHY {self.p.trophies & 0x7F:02d}", (W - 160, 48), MID)

        if self.message:
            r.text(small, self.message, (CX, 92), WHITE, True)

    def draw_trophy_room(self, r, big, small):
        room2 = bool(self.p.trophies & 0x80)
        r.text(
            big,
            "TROPHY ROOM 2" if room2 else "TROPHY ROOM",
            (CX, 70),
            WHITE,
            True
        )

        count = self.p.trophies & 0x7F
        max_show = min(count, 32 if self.original_trophy_bug else 20)

        for i in range(max_show):
            row, col = divmod(i, 4)
            origin = (105 + col * 170, 180 + row * 105)

            if i < 20:
                r.original_mode_list(
                    self.a.trophy(i, (self.frame // 12) & 1),
                    origin,
                    10,
                    0,
                    MID
                )
            else:
                # Faithful semantic representation of original out-of-table
                # garbage. Exact garbage decode can be added once Trophy Room
                # list reading is fully transcribed.
                r.original_mode_list(
                    self.a.vector("112C_pattern_x_cross"),
                    origin,
                    8,
                    u8(i * 3),
                    DIM
                )

        r.text(small, "1 / 2 TO EXIT", (CX, H - 55), MID, True)

    def draw_gameover(self, r, big, mid):
        r.text(big, "GAME OVER", (CX, 300), WHITE, True)
        r.text(mid, f"PLAYER 1  {self.players[0].score:06d}", (CX, 610), MID, True)
        if self.num_players == 2:
            r.text(mid, f"PLAYER 2  {self.players[1].score:06d}", (CX, 480), MID, True)
        r.text(mid, "R / SPACE", (CX, 610), DIM, True)

    def draw_debug(self, r, tiny):
        if not self.debug:
            return

        origin, transformed, disps = self.object_origin(self.hawk)

        lines = [
            f"BIOS ROT TABLE {'ROM' if self.a.bios is not None else 'EMBEDDED'}",
            f"B5=${self.web_angle_word:04X} angleByte=${self.camera_angle_byte():02X}",
            f"A0=${self.camera_a:04X} A2=${self.camera_b:04X}",
            f"script {self.web_script_i}/{len(self.a.web_script)} t={self.web_script_timer} (deterministic)",
            f"web front rail target=$E000",
            f"hawk seg={self.hawk.segment} sub={self.hawk.subindex:02d}/32",
            f"hawk world Y=${self.hawk.world_y:04X} X=${self.hawk.world_x:04X}",
            f"hawk xform=({transformed[0]:+d},{transformed[1]:+d})",
            f"$094F disp={disps[0]} {disps[1]}",
            f"origin=({origin[0]:.1f},{origin[1]:.1f}) depth=${self.hawk.depth:04X}",
            f"speed={self.speed} webdelay={self.current_web_delay():02X}",
            f"web lines={sum(x['active'] for x in self.web_lines)}/9",
            f"guardians={sum(g.active and g.state>0 for g in self.guardians)}/6",
            f"shots={sum(s.active for s in self.shots)}/9 rod={self.hawk_rod_timer}/13",
        ]

        y = 88
        for line in lines:
            r.text(tiny, line, (10, y), DIM)
            y += 17

    def draw(self, screen, fonts, keys):
        r = Renderer(screen, self.bm)
        big, mid, small, tiny = fonts

        if self.state == "TITLE":
            self.draw_title(r, big, mid, small, keys)

        elif self.state == "SELECT":
            self.draw_select(r, big, mid)

        elif self.state == "PLAY":
            self.draw_web(r)
            self.draw_shots(r)
            self.draw_guardians(r)
            self.draw_creature(r)
            self.draw_portal(r)
            self.draw_dragon(r)
            self.draw_hawk(r)
            self.draw_hud(r, small)
            self.draw_debug(r, tiny)

        elif self.state == "TROPHY":
            self.draw_trophy_room(r, big, small)

        elif self.state == "GAMEOVER":
            self.draw_gameover(r, big, mid)

        if self.paused:
            r.text(big, "PAUSED", (CX, CY), WHITE, True)


# ---------------------------------------------------------------------------
# Self test
# ---------------------------------------------------------------------------

def locate(paths):
    for p in paths:
        q = Path(p)
        if q.exists():
            return q
    return None


def self_test(a: Assets):
    bm = BiosMath(a)

    assert a.score_guardian == 75
    assert a.score_capture == 325
    assert a.score_trophy == 750
    assert len(a.web_script) == 15
    assert len(a.vertex_words) == 8
    assert len(a.motion8) == 7
    assert len(a.motion16) == 7
    assert len(a.motion32) == 7
    assert len(a.trophy_keys) == 40

    assert a.rotation_table == Assets.FALLBACK_ROTATION_TABLE

    # ROM starts speed at trophies+4; with zero trophies speed=4 and
    # table_delays_between_web_lines-1 indexing selects $2A.
    _tmp_game = Game(a)
    _tmp_game.speed = 4
    assert _tmp_game.current_web_delay() == 0x2A

    # $1177 first and last cumulative vertices.
    assert a.vertex_words[0] == (0x3000, 0x5000)
    assert a.vertex_words[-1] == (0x3000, 0xB000)

    # Central segment midpoint = Y -48, X 0.
    mid = a.midpoint(3)
    assert mid == (0xD000, 0x0000)

    # Angle zero: rise is identity, run zero.
    assert bm.transform_pair(-48, 0, 0) == (-48, 0)

    # $094F with zero camera splits -48 into two -24 moves.
    assert build_draw_displacement(0, 0, -48, 0) == ((-24, 0), (-24, 0))

    # Exact rounded depth rule.
    d = advance_depth(0x0280, 4, False)
    assert d == ((0x0280 + (((0x0280 * 4) + 0x80) >> 8)) & 0xFFFF)

    # Movement step table exactly traverses a segment in 32 steps.
    y, x = a.vertex_words[3]
    dy, dx = a.motion8[3]
    for _ in range(32):
        y = u16(y + dy)
        x = u16(x + dx)
    assert (y, x) == a.vertex_words[4]

    # Portrait display contract.
    assert (W, H) == (720, 960)
    assert H > W

    # The $191C web camera script is fixed cartridge data, not random.
    assert a.web_script[0] == (127, 0, 0, 0)
    assert a.web_script[1] == (48, 0, -192, 4)
    assert a.web_script[2] == (48, 0, 0, 8)

    # Display calibration only: original $1177 spans 160 X-units.
    # At scale $E0 and gain 1.0 this should map to exactly 560 logical pixels.
    if abs(HW_TO_PIXELS - BASE_HW_TO_PIXELS) < 1e-12:
        assert abs(160 * 0xE0 * HW_TO_PIXELS - 560.0) < 1e-9

    # $094F exact byte-shift regression:
    # with zero camera and transformed (-48,0), each move is (-24,0).
    assert build_draw_displacement(0, 0, -48, 0) == ((-24, 0), (-24, 0))

    # Odd B value proves ASRB is independent rather than RORB from A carry.
    odd = build_draw_displacement(0, 0, 1, 1)
    assert odd == ((0, 0), (1, 1)), odd

    # Camera pre-move must be present in object placement.
    g = Game(a)
    g.camera_a = 0x1800
    g.camera_b = 0xE800
    g.web_angle_word = 0
    g.hawk.depth = 0xE000
    g.hawk.world_y, g.hawk.world_x = a.midpoint(3)
    cam = g.camera_pre_move((CX, CY))
    assert cam != (CX, CY)
    hp, _, _ = g.object_origin(g.hawk)
    assert hp != (CX, CY)

    # Ring initial positioning: with zero camera the separately transformed
    # first $1177 MOVE must be equivalent to moving to (48,80), not executing
    # that MOVE again inside Draw_VLp.
    g.camera_a = 0
    g.camera_b = 0
    g.web_angle_word = 0
    _p1, _p2 = g.web_initial_vertex_displacement()
    assert _p1 == (24, 40), (_p1, _p2)
    assert _p2 == (24, 40), (_p1, _p2)

    _ring = g.web_ring_points(0x4000)
    assert len(_ring) == 8
    # U is symmetric in Y endpoints under angle 0.
    assert _ring[0][1] == _ring[-1][1]

    # Foreground continuation has eight corresponding endpoints at fixed $E0.
    _front = g.web_ring_points(0xE000)
    assert len(_front) == 8
    # It must extend farther from center than a mid-depth ring.
    _ring_span = max(p[0] for p in _ring) - min(p[0] for p in _ring)
    _front_span = max(p[0] for p in _front) - min(p[0] for p in _front)
    assert _front_span > _ring_span

    # Original-style prefill should start play with several receding rings.
    active_depths = sorted(
        (rec["depth"] for rec in g.web_lines if rec["active"]),
        reverse=True
    )
    assert len(active_depths) >= 4, active_depths
    assert all(hi(d) <= 0xE0 for d in active_depths)

    print("SELF-TEST OK")
    print("title:", a.title)
    print("BIOS rotation table source:", "BIOS ROM" if a.bios is not None else "embedded fallback")
    print("rotation table:", a.rotation_table)
    print("center segment midpoint: Y=$%04X X=$%04X" % mid)
    print("angle 0 transform (-48,0):", bm.transform_pair(-48, 0, 0))
    print("$094F initial player displacement:",
          build_draw_displacement(0, 0, -48, 0))
    print("motion8 segment 3:", tuple(s16(v) for v in a.motion8[3]))
    print("32 steps exactly reach next vertex: OK")
    print("display:", W, "x", H, "(3:4 portrait)")
    print("beam factor:", HW_TO_PIXELS, "(gain %.3f)" % (HW_TO_PIXELS / BASE_HW_TO_PIXELS))
    print("full $E0 web width:", 160 * 0xE0 * HW_TO_PIXELS, "logical px")
    print("$094F independent ASRA/ASRB: OK")
    print("camera pre-move @ $7F: OK")
    print("$1177 initial MOVE separated from Draw_VLp: OK")
    print("$191C web motion script: deterministic, not random")
    print("fixed-$E0 foreground rail continuation: OK")
    print("startup web prefill depths:",
          ["$%04X" % d for d in active_depths])
    print("window line clipping: enabled")
    print("scores:", a.score_guardian, a.score_capture, a.score_trophy)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom")
    ap.add_argument("--vectors")
    ap.add_argument("--bios")
    ap.add_argument(
        "--beam-gain",
        type=float,
        default=1.0,
        help="final analogue display gain only; 1.0 = calibrated V7 default"
    )
    ap.add_argument("--self-test", action="store_true")
    ns = ap.parse_args()

    global HW_TO_PIXELS
    if not (0.5 <= ns.beam_gain <= 2.0):
        raise SystemExit("--beam-gain must be between 0.5 and 2.0")
    HW_TO_PIXELS = BASE_HW_TO_PIXELS * ns.beam_gain

    here = Path(__file__).resolve().parent

    rom = Path(ns.rom) if ns.rom else locate([
        here / "Web Warp (1983).vec",
        Path("/mnt/data/Web Warp (1983).vec"),
    ])

    vectors = Path(ns.vectors) if ns.vectors else locate([
        here / "web_warp_vectors.json",
        here / "web_warp_vectors(1).json",
        Path("/mnt/data/web_warp_vectors.json"),
        Path("/mnt/data/web_warp_vectors(1).json"),
    ])

    bios = Path(ns.bios) if ns.bios else locate([
        here / "Vectrex BIOS (1982)(5).vec",
        here / "Vectrex BIOS (1982).vec",
        Path("/mnt/data/Vectrex BIOS (1982)(5).vec"),
    ])

    if rom is None or not rom.exists():
        raise SystemExit("Web Warp ROM not found")
    if vectors is None or not vectors.exists():
        raise SystemExit("web_warp_vectors.json not found")

    a = Assets(rom, vectors, bios)

    if ns.self_test:
        self_test(a)
        return

    require_pygame()

    pygame.init()
    screen = pygame.display.set_mode((W, H))
    pygame.display.set_caption("Web Warp — Python vector reconstruction V8 — foreground web fixed")
    clock = pygame.time.Clock()

    fonts = (
        pygame.font.Font(None, 62),
        pygame.font.Font(None, 36),
        pygame.font.Font(None, 27),
        pygame.font.Font(None, 19),
    )

    game = Game(a)
    running = True

    try:
        while running:
            for ev in pygame.event.get():
                if ev.type == pygame.QUIT:
                    running = False
                    break
                if not game.handle_event(ev):
                    running = False
                    break

            # Do not execute another potentially expensive update/draw after X.
            if not running:
                break

            keys = pygame.key.get_pressed()
            game.update(keys)

            screen.fill(BLACK)
            game.draw(screen, fonts, keys)
            pygame.display.flip()
            clock.tick(FPS)

    except KeyboardInterrupt:
        pass
    finally:
        pygame.display.quit()
        pygame.quit()


if __name__ == "__main__":
    main()
